# Generated by Django 4.2.3 on 2023-07-20 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0003_client_owner_logmessage_message_setmessage_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logmessage',
            options={'ordering': ('status_try',), 'verbose_name': 'лог рассылки', 'verbose_name_plural': 'логи рассылки'},
        ),
        migrations.AlterModelOptions(
            name='setmessage',
            options={'ordering': ('mailing_time',), 'verbose_name': 'настройка рассылки', 'verbose_name_plural': 'настройки рассылки'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='owner',
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='comment',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='комментарий'),
        ),
    ]
